export type MuscleGroup =
  | "chest"
  | "back"
  | "shoulders"
  | "biceps"
  | "triceps"
  | "quads"
  | "hamstrings"
  | "glutes"
  | "calves"
  | "core"
  | "cardio";

export type Equipment =
  | "bodyweight"
  | "dumbbell"
  | "barbell"
  | "machine"
  | "bands"
  | "kettlebell";

export type Difficulty = "beginner" | "intermediate" | "advanced";

export interface Exercise {
  id: string;
  name: string;
  muscleGroup: MuscleGroup;
  equipment: Equipment;
  difficulty: Difficulty;
  /** @deprecated use `cues` (array) instead — kept for backward compatibility */
  cue: string;
  /** Form cues, in priority order. First one mirrors `cue`. */
  cues: string[];
  /** Common technique errors to watch for. */
  commonMistakes: string[];
  /** IDs of other exercises that train the same muscle group with different equipment. */
  alternatives: string[];
  /** ID of an easier variation, if one exists in the library. */
  progressionEasier: string | null;
  /** ID of a harder variation, if one exists in the library. */
  progressionHarder: string | null;
  /** Not yet available — needs licensed footage or filmed content. */
  videoUrl: string | null;
}

export const EXERCISES: Exercise[] = [

  // Chest
  { id: "pushup", name: "Push-Up", muscleGroup: "chest", equipment: "bodyweight", difficulty: "beginner", cue: "Keep core tight, elbows ~45°", cues: ["Keep core tight, elbows ~45°", "Keep elbows at roughly 45° from your torso, not flared to 90°", "Brace your core so hips don't sag"], commonMistakes: ["Flaring elbows straight out to the sides, stressing the shoulders", "Letting hips sag or pike up instead of staying in a straight line"], alternatives: ["chest-press-machine", "band-chest-press"], progressionEasier: null, progressionHarder: "db-bench-press", videoUrl: null },
  { id: "incline-pushup", name: "Incline Push-Up", muscleGroup: "chest", equipment: "bodyweight", difficulty: "beginner", cue: "Hands elevated on bench for easier variant", cues: ["Hands elevated on bench for easier variant", "Keep elbows at roughly 45° from your torso, not flared to 90°", "Brace your core so hips don't sag"], commonMistakes: ["Flaring elbows straight out to the sides, stressing the shoulders", "Letting hips sag or pike up instead of staying in a straight line"], alternatives: ["chest-press-machine", "band-chest-press"], progressionEasier: null, progressionHarder: "db-bench-press", videoUrl: null },
  { id: "db-bench-press", name: "Dumbbell Bench Press", muscleGroup: "chest", equipment: "dumbbell", difficulty: "intermediate", cue: "Control the descent, press up smoothly", cues: ["Control the descent, press up smoothly", "Keep elbows at roughly 45° from your torso, not flared to 90°", "Brace your core so hips don't sag"], commonMistakes: ["Flaring elbows straight out to the sides, stressing the shoulders", "Letting hips sag or pike up instead of staying in a straight line"], alternatives: ["pushup", "incline-pushup"], progressionEasier: "pushup", progressionHarder: "barbell-bench-press", videoUrl: null },
  { id: "db-flye", name: "Dumbbell Chest Flye", muscleGroup: "chest", equipment: "dumbbell", difficulty: "intermediate", cue: "Slight elbow bend throughout", cues: ["Slight elbow bend throughout", "Keep a slight, fixed bend in the elbows throughout", "Lower until you feel a stretch across the chest, not the shoulders"], commonMistakes: ["Bending and straightening the elbows like a press instead of a flye", "Going so heavy that the shoulders take over the movement"], alternatives: ["pushup", "incline-pushup"], progressionEasier: "pushup", progressionHarder: "barbell-bench-press", videoUrl: null },
  { id: "barbell-bench-press", name: "Barbell Bench Press", muscleGroup: "chest", equipment: "barbell", difficulty: "advanced", cue: "Retract shoulder blades, feet planted", cues: ["Retract shoulder blades, feet planted", "Keep elbows at roughly 45° from your torso, not flared to 90°", "Brace your core so hips don't sag"], commonMistakes: ["Flaring elbows straight out to the sides, stressing the shoulders", "Letting hips sag or pike up instead of staying in a straight line"], alternatives: ["db-bench-press", "db-flye"], progressionEasier: "db-bench-press", progressionHarder: null, videoUrl: null },
  { id: "chest-press-machine", name: "Chest Press Machine", muscleGroup: "chest", equipment: "machine", difficulty: "beginner", cue: "Adjust seat so handles align with chest", cues: ["Adjust seat so handles align with chest", "Keep elbows at roughly 45° from your torso, not flared to 90°", "Brace your core so hips don't sag"], commonMistakes: ["Flaring elbows straight out to the sides, stressing the shoulders", "Letting hips sag or pike up instead of staying in a straight line"], alternatives: ["pushup", "incline-pushup"], progressionEasier: null, progressionHarder: "db-bench-press", videoUrl: null },
  { id: "band-chest-press", name: "Band Chest Press", muscleGroup: "chest", equipment: "bands", difficulty: "beginner", cue: "Anchor band behind you, press forward", cues: ["Anchor band behind you, press forward", "Keep elbows at roughly 45° from your torso, not flared to 90°", "Brace your core so hips don't sag"], commonMistakes: ["Flaring elbows straight out to the sides, stressing the shoulders", "Letting hips sag or pike up instead of staying in a straight line"], alternatives: ["pushup", "incline-pushup"], progressionEasier: null, progressionHarder: "db-bench-press", videoUrl: null },

  // Back
  { id: "bodyweight-row", name: "Inverted Row", muscleGroup: "back", equipment: "bodyweight", difficulty: "intermediate", cue: "Body straight, pull chest to bar", cues: ["Body straight, pull chest to bar", "Pull your elbow back past your torso, not just up", "Squeeze the shoulder blade at the end of the pull"], commonMistakes: ["Using momentum/body swing to move the weight", "Shrugging the shoulder up toward the ear instead of pulling with the back"], alternatives: ["db-pullover", "kb-row"], progressionEasier: "superman", progressionHarder: "barbell-row", videoUrl: null },
  { id: "superman", name: "Superman Hold", muscleGroup: "back", equipment: "bodyweight", difficulty: "beginner", cue: "Lift chest and legs, squeeze glutes", cues: ["Lift chest and legs, squeeze glutes", "Lift chest and legs simultaneously, squeezing the glutes and lower back", "Keep the neck neutral — don't crane it upward"], commonMistakes: ["Overextending the lower back by lifting too high", "Rushing the reps instead of holding the peak contraction"], alternatives: ["db-row", "lat-pulldown"], progressionEasier: null, progressionHarder: "bodyweight-row", videoUrl: null },
  { id: "db-row", name: "Dumbbell Row", muscleGroup: "back", equipment: "dumbbell", difficulty: "beginner", cue: "Flat back, pull elbow past torso", cues: ["Flat back, pull elbow past torso", "Pull your elbow back past your torso, not just up", "Squeeze the shoulder blade at the end of the pull"], commonMistakes: ["Using momentum/body swing to move the weight", "Shrugging the shoulder up toward the ear instead of pulling with the back"], alternatives: ["superman", "lat-pulldown"], progressionEasier: null, progressionHarder: "bodyweight-row", videoUrl: null },
  { id: "db-pullover", name: "Dumbbell Pullover", muscleGroup: "back", equipment: "dumbbell", difficulty: "intermediate", cue: "Keep slight elbow bend, feel the stretch", cues: ["Keep slight elbow bend, feel the stretch", "Keep a slight, fixed bend in the elbows", "Lower the weight behind your head until you feel a stretch in the lats"], commonMistakes: ["Bending the elbows more as the weight lowers, turning it into a triceps move", "Using a weight too heavy to control through the full stretch"], alternatives: ["bodyweight-row", "kb-row"], progressionEasier: "superman", progressionHarder: "barbell-row", videoUrl: null },
  { id: "barbell-row", name: "Barbell Bent-Over Row", muscleGroup: "back", equipment: "barbell", difficulty: "advanced", cue: "Hinge at hips, neutral spine", cues: ["Hinge at hips, neutral spine", "Pull your elbow back past your torso, not just up", "Squeeze the shoulder blade at the end of the pull"], commonMistakes: ["Using momentum/body swing to move the weight", "Shrugging the shoulder up toward the ear instead of pulling with the back"], alternatives: ["bodyweight-row", "db-pullover"], progressionEasier: "bodyweight-row", progressionHarder: null, videoUrl: null },
  { id: "lat-pulldown", name: "Lat Pulldown Machine", muscleGroup: "back", equipment: "machine", difficulty: "beginner", cue: "Pull bar to upper chest, control the return", cues: ["Pull bar to upper chest, control the return", "Initiate the pull by driving your elbows down and back", "Bring the bar/chest together without leaning back excessively"], commonMistakes: ["Using only the arms and skipping the lat engagement", "Kipping or swinging to get the rep up on a chin-up"], alternatives: ["superman", "db-row"], progressionEasier: null, progressionHarder: "bodyweight-row", videoUrl: null },
  { id: "band-row", name: "Band Seated Row", muscleGroup: "back", equipment: "bands", difficulty: "beginner", cue: "Squeeze shoulder blades at the end", cues: ["Squeeze shoulder blades at the end", "Pull your elbow back past your torso, not just up", "Squeeze the shoulder blade at the end of the pull"], commonMistakes: ["Using momentum/body swing to move the weight", "Shrugging the shoulder up toward the ear instead of pulling with the back"], alternatives: ["superman", "db-row"], progressionEasier: null, progressionHarder: "bodyweight-row", videoUrl: null },
  { id: "kb-row", name: "Kettlebell Row", muscleGroup: "back", equipment: "kettlebell", difficulty: "intermediate", cue: "Brace core, pull to hip", cues: ["Brace core, pull to hip", "Pull your elbow back past your torso, not just up", "Squeeze the shoulder blade at the end of the pull"], commonMistakes: ["Using momentum/body swing to move the weight", "Shrugging the shoulder up toward the ear instead of pulling with the back"], alternatives: ["bodyweight-row", "db-pullover"], progressionEasier: "superman", progressionHarder: "barbell-row", videoUrl: null },

  // Shoulders
  { id: "pike-pushup", name: "Pike Push-Up", muscleGroup: "shoulders", equipment: "bodyweight", difficulty: "intermediate", cue: "Hips high, head toward floor", cues: ["Hips high, head toward floor", "Brace your core to avoid arching the lower back", "Press in a straight line, finishing with the weight over your head"], commonMistakes: ["Excessively arching the back to help the weight up", "Flaring elbows too wide at the bottom position"], alternatives: ["kb-press", "db-shoulder-press"], progressionEasier: "db-shoulder-press", progressionHarder: "barbell-ohp", videoUrl: null },
  { id: "db-shoulder-press", name: "Dumbbell Shoulder Press", muscleGroup: "shoulders", equipment: "dumbbell", difficulty: "beginner", cue: "Press straight up, avoid arching back", cues: ["Press straight up, avoid arching back", "Brace your core to avoid arching the lower back", "Press in a straight line, finishing with the weight over your head"], commonMistakes: ["Excessively arching the back to help the weight up", "Flaring elbows too wide at the bottom position"], alternatives: ["shoulder-press-machine", "band-lateral-raise"], progressionEasier: null, progressionHarder: "pike-pushup", videoUrl: null },
  { id: "db-lateral-raise", name: "Dumbbell Lateral Raise", muscleGroup: "shoulders", equipment: "dumbbell", difficulty: "beginner", cue: "Slight bend in elbows, lead with elbows", cues: ["Slight bend in elbows, lead with elbows", "Lead with your elbows, not your hands", "Raise only to shoulder height — no higher"], commonMistakes: ["Using momentum/swinging the torso to fling the weight up", "Going too heavy and turning it into a front raise/shrug"], alternatives: ["shoulder-press-machine", "band-lateral-raise"], progressionEasier: null, progressionHarder: "pike-pushup", videoUrl: null },
  { id: "barbell-ohp", name: "Barbell Overhead Press", muscleGroup: "shoulders", equipment: "barbell", difficulty: "advanced", cue: "Brace core, press bar in straight line", cues: ["Brace core, press bar in straight line", "Brace your core to avoid arching the lower back", "Press in a straight line, finishing with the weight over your head"], commonMistakes: ["Excessively arching the back to help the weight up", "Flaring elbows too wide at the bottom position"], alternatives: ["pike-pushup", "kb-press"], progressionEasier: "pike-pushup", progressionHarder: null, videoUrl: null },
  { id: "shoulder-press-machine", name: "Shoulder Press Machine", muscleGroup: "shoulders", equipment: "machine", difficulty: "beginner", cue: "Full range, controlled tempo", cues: ["Full range, controlled tempo", "Brace your core to avoid arching the lower back", "Press in a straight line, finishing with the weight over your head"], commonMistakes: ["Excessively arching the back to help the weight up", "Flaring elbows too wide at the bottom position"], alternatives: ["db-shoulder-press", "db-lateral-raise"], progressionEasier: null, progressionHarder: "pike-pushup", videoUrl: null },
  { id: "band-lateral-raise", name: "Band Lateral Raise", muscleGroup: "shoulders", equipment: "bands", difficulty: "beginner", cue: "Stand on band, raise to shoulder height", cues: ["Stand on band, raise to shoulder height", "Lead with your elbows, not your hands", "Raise only to shoulder height — no higher"], commonMistakes: ["Using momentum/swinging the torso to fling the weight up", "Going too heavy and turning it into a front raise/shrug"], alternatives: ["db-shoulder-press", "db-lateral-raise"], progressionEasier: null, progressionHarder: "pike-pushup", videoUrl: null },
  { id: "kb-press", name: "Kettlebell Press", muscleGroup: "shoulders", equipment: "kettlebell", difficulty: "intermediate", cue: "Rack position, drive straight up", cues: ["Rack position, drive straight up", "Brace your core to avoid arching the lower back", "Press in a straight line, finishing with the weight over your head"], commonMistakes: ["Excessively arching the back to help the weight up", "Flaring elbows too wide at the bottom position"], alternatives: ["pike-pushup", "db-shoulder-press"], progressionEasier: "db-shoulder-press", progressionHarder: "barbell-ohp", videoUrl: null },

  // Biceps
  { id: "chinup", name: "Chin-Up", muscleGroup: "biceps", equipment: "bodyweight", difficulty: "advanced", cue: "Underhand grip, chest to bar", cues: ["Underhand grip, chest to bar", "Initiate the pull by driving your elbows down and back", "Bring the bar/chest together without leaning back excessively"], commonMistakes: ["Using only the arms and skipping the lat engagement", "Kipping or swinging to get the rep up on a chin-up"], alternatives: ["barbell-curl", "db-curl"], progressionEasier: "barbell-curl", progressionHarder: null, videoUrl: null },
  { id: "db-curl", name: "Dumbbell Bicep Curl", muscleGroup: "biceps", equipment: "dumbbell", difficulty: "beginner", cue: "Elbows pinned to sides", cues: ["Elbows pinned to sides", "Keep your elbows pinned to your sides", "Squeeze at the top without swinging the torso"], commonMistakes: ["Swinging the body to generate momentum ('cheat curls')", "Letting the elbows drift forward, turning it into a front raise"], alternatives: ["band-curl", "kb-curl"], progressionEasier: null, progressionHarder: "barbell-curl", videoUrl: null },
  { id: "barbell-curl", name: "Barbell Curl", muscleGroup: "biceps", equipment: "barbell", difficulty: "intermediate", cue: "No swinging, controlled tempo", cues: ["No swinging, controlled tempo", "Keep your elbows pinned to your sides", "Squeeze at the top without swinging the torso"], commonMistakes: ["Swinging the body to generate momentum ('cheat curls')", "Letting the elbows drift forward, turning it into a front raise"], alternatives: ["chinup", "db-curl"], progressionEasier: "db-curl", progressionHarder: "chinup", videoUrl: null },
  { id: "band-curl", name: "Band Bicep Curl", muscleGroup: "biceps", equipment: "bands", difficulty: "beginner", cue: "Stand on band, curl to shoulder", cues: ["Stand on band, curl to shoulder", "Keep your elbows pinned to your sides", "Squeeze at the top without swinging the torso"], commonMistakes: ["Swinging the body to generate momentum ('cheat curls')", "Letting the elbows drift forward, turning it into a front raise"], alternatives: ["db-curl", "kb-curl"], progressionEasier: null, progressionHarder: "barbell-curl", videoUrl: null },
  { id: "kb-curl", name: "Kettlebell Curl", muscleGroup: "biceps", equipment: "kettlebell", difficulty: "beginner", cue: "Neutral grip, slow negative", cues: ["Neutral grip, slow negative", "Keep your elbows pinned to your sides", "Squeeze at the top without swinging the torso"], commonMistakes: ["Swinging the body to generate momentum ('cheat curls')", "Letting the elbows drift forward, turning it into a front raise"], alternatives: ["db-curl", "band-curl"], progressionEasier: null, progressionHarder: "barbell-curl", videoUrl: null },

  // Triceps
  { id: "tricep-dip", name: "Bench Tricep Dip", muscleGroup: "triceps", equipment: "bodyweight", difficulty: "intermediate", cue: "Elbows track backward, not out", cues: ["Elbows track backward, not out", "Keep your upper arm still — only the forearm moves", "Get a full stretch at the bottom before pressing back up"], commonMistakes: ["Letting the elbows flare out or drift forward during the movement", "Using body momentum instead of isolating the triceps"], alternatives: ["db-tricep-extension", "db-kickback"], progressionEasier: "db-tricep-extension", progressionHarder: "diamond-pushup", videoUrl: null },
  { id: "diamond-pushup", name: "Diamond Push-Up", muscleGroup: "triceps", equipment: "bodyweight", difficulty: "advanced", cue: "Hands form diamond shape under chest", cues: ["Hands form diamond shape under chest", "Keep elbows at roughly 45° from your torso, not flared to 90°", "Brace your core so hips don't sag"], commonMistakes: ["Flaring elbows straight out to the sides, stressing the shoulders", "Letting hips sag or pike up instead of staying in a straight line"], alternatives: ["db-tricep-extension", "db-kickback"], progressionEasier: "tricep-dip", progressionHarder: null, videoUrl: null },
  { id: "db-tricep-extension", name: "Dumbbell Overhead Extension", muscleGroup: "triceps", equipment: "dumbbell", difficulty: "beginner", cue: "Elbows close to head, full stretch", cues: ["Elbows close to head, full stretch", "Keep your upper arm still — only the forearm moves", "Get a full stretch at the bottom before pressing back up"], commonMistakes: ["Letting the elbows flare out or drift forward during the movement", "Using body momentum instead of isolating the triceps"], alternatives: ["tricep-pushdown", "band-pushdown"], progressionEasier: null, progressionHarder: "tricep-dip", videoUrl: null },
  { id: "db-kickback", name: "Dumbbell Kickback", muscleGroup: "triceps", equipment: "dumbbell", difficulty: "beginner", cue: "Upper arm parallel to floor", cues: ["Upper arm parallel to floor", "Keep your upper arm still — only the forearm moves", "Get a full stretch at the bottom before pressing back up"], commonMistakes: ["Letting the elbows flare out or drift forward during the movement", "Using body momentum instead of isolating the triceps"], alternatives: ["tricep-pushdown", "band-pushdown"], progressionEasier: null, progressionHarder: "tricep-dip", videoUrl: null },
  { id: "tricep-pushdown", name: "Cable/Machine Tricep Pushdown", muscleGroup: "triceps", equipment: "machine", difficulty: "beginner", cue: "Elbows pinned, full extension", cues: ["Elbows pinned, full extension", "Keep your upper arm still — only the forearm moves", "Get a full stretch at the bottom before pressing back up"], commonMistakes: ["Letting the elbows flare out or drift forward during the movement", "Using body momentum instead of isolating the triceps"], alternatives: ["db-tricep-extension", "db-kickback"], progressionEasier: null, progressionHarder: "tricep-dip", videoUrl: null },
  { id: "band-pushdown", name: "Band Tricep Pushdown", muscleGroup: "triceps", equipment: "bands", difficulty: "beginner", cue: "Anchor overhead, push down", cues: ["Anchor overhead, push down", "Keep your upper arm still — only the forearm moves", "Get a full stretch at the bottom before pressing back up"], commonMistakes: ["Letting the elbows flare out or drift forward during the movement", "Using body momentum instead of isolating the triceps"], alternatives: ["db-tricep-extension", "db-kickback"], progressionEasier: null, progressionHarder: "tricep-dip", videoUrl: null },

  // Quads
  { id: "bodyweight-squat", name: "Bodyweight Squat", muscleGroup: "quads", equipment: "bodyweight", difficulty: "beginner", cue: "Knees track over toes, chest up", cues: ["Knees track over toes, chest up", "Knees track in line with your toes, not caving inward", "Keep your chest up and core braced throughout"], commonMistakes: ["Knees caving inward (valgus collapse) under load", "Rising with hips first, turning it into a good-morning instead of a squat"], alternatives: ["db-goblet-squat", "leg-press"], progressionEasier: null, progressionHarder: "db-lunge", videoUrl: null },
  { id: "lunge", name: "Walking Lunge", muscleGroup: "quads", equipment: "bodyweight", difficulty: "beginner", cue: "Front knee at 90°, torso upright", cues: ["Front knee at 90°, torso upright", "Front knee tracks over the ankle, not past the toes", "Keep your torso upright rather than leaning forward"], commonMistakes: ["Letting the front knee cave inward on the way up", "Taking too short a step, putting excess stress on the front knee"], alternatives: ["db-goblet-squat", "leg-press"], progressionEasier: null, progressionHarder: "db-lunge", videoUrl: null },
  { id: "jump-squat", name: "Jump Squat", muscleGroup: "quads", equipment: "bodyweight", difficulty: "advanced", cue: "Soft landing, full squat depth", cues: ["Soft landing, full squat depth", "Knees track in line with your toes, not caving inward", "Keep your chest up and core braced throughout"], commonMistakes: ["Knees caving inward (valgus collapse) under load", "Rising with hips first, turning it into a good-morning instead of a squat"], alternatives: ["barbell-squat", "db-lunge"], progressionEasier: "db-lunge", progressionHarder: null, videoUrl: null },
  { id: "db-goblet-squat", name: "Dumbbell Goblet Squat", muscleGroup: "quads", equipment: "dumbbell", difficulty: "beginner", cue: "Hold weight at chest, sit back and down", cues: ["Hold weight at chest, sit back and down", "Knees track in line with your toes, not caving inward", "Keep your chest up and core braced throughout"], commonMistakes: ["Knees caving inward (valgus collapse) under load", "Rising with hips first, turning it into a good-morning instead of a squat"], alternatives: ["bodyweight-squat", "lunge"], progressionEasier: null, progressionHarder: "db-lunge", videoUrl: null },
  { id: "db-lunge", name: "Dumbbell Lunge", muscleGroup: "quads", equipment: "dumbbell", difficulty: "intermediate", cue: "Control the descent", cues: ["Control the descent", "Front knee tracks over the ankle, not past the toes", "Keep your torso upright rather than leaning forward"], commonMistakes: ["Letting the front knee cave inward on the way up", "Taking too short a step, putting excess stress on the front knee"], alternatives: ["bodyweight-squat", "lunge"], progressionEasier: "bodyweight-squat", progressionHarder: "jump-squat", videoUrl: null },
  { id: "barbell-squat", name: "Barbell Back Squat", muscleGroup: "quads", equipment: "barbell", difficulty: "advanced", cue: "Bar on upper back, hips and chest rise together", cues: ["Bar on upper back, hips and chest rise together", "Knees track in line with your toes, not caving inward", "Keep your chest up and core braced throughout"], commonMistakes: ["Knees caving inward (valgus collapse) under load", "Rising with hips first, turning it into a good-morning instead of a squat"], alternatives: ["jump-squat", "db-lunge"], progressionEasier: "db-lunge", progressionHarder: null, videoUrl: null },
  { id: "leg-press", name: "Leg Press Machine", muscleGroup: "quads", equipment: "machine", difficulty: "beginner", cue: "Don't lock out knees at top", cues: ["Don't lock out knees at top", "Knees track in line with your toes, not caving inward", "Keep your chest up and core braced throughout"], commonMistakes: ["Knees caving inward (valgus collapse) under load", "Rising with hips first, turning it into a good-morning instead of a squat"], alternatives: ["bodyweight-squat", "lunge"], progressionEasier: null, progressionHarder: "db-lunge", videoUrl: null },
  { id: "kb-goblet-squat", name: "Kettlebell Goblet Squat", muscleGroup: "quads", equipment: "kettlebell", difficulty: "beginner", cue: "Elbows inside knees at bottom", cues: ["Elbows inside knees at bottom", "Knees track in line with your toes, not caving inward", "Keep your chest up and core braced throughout"], commonMistakes: ["Knees caving inward (valgus collapse) under load", "Rising with hips first, turning it into a good-morning instead of a squat"], alternatives: ["bodyweight-squat", "lunge"], progressionEasier: null, progressionHarder: "db-lunge", videoUrl: null },
  { id: "band-squat", name: "Band Squat", muscleGroup: "quads", equipment: "bands", difficulty: "beginner", cue: "Band under feet, held at shoulders", cues: ["Band under feet, held at shoulders", "Knees track in line with your toes, not caving inward", "Keep your chest up and core braced throughout"], commonMistakes: ["Knees caving inward (valgus collapse) under load", "Rising with hips first, turning it into a good-morning instead of a squat"], alternatives: ["bodyweight-squat", "lunge"], progressionEasier: null, progressionHarder: "db-lunge", videoUrl: null },

  // Glutes
  { id: "glute-bridge", name: "Glute Bridge", muscleGroup: "glutes", equipment: "bodyweight", difficulty: "beginner", cue: "Squeeze glutes at the top", cues: ["Squeeze glutes at the top", "Squeeze the glutes hard at the top of the movement", "Avoid overarching the lower back to get more range"], commonMistakes: ["Using lower back extension instead of glute contraction to move the weight", "Rushing through reps without pausing at peak contraction"], alternatives: ["db-step-up", "band-glute-kickback"], progressionEasier: null, progressionHarder: "kb-swing", videoUrl: null },

  // Hamstrings
  { id: "single-leg-rdl", name: "Single-Leg RDL (bodyweight)", muscleGroup: "hamstrings", equipment: "bodyweight", difficulty: "intermediate", cue: "Hinge at hips, back flat", cues: ["Hinge at hips, back flat", "Push your hips back first, keeping a soft bend in the knees", "Keep the bar/weight close to your legs throughout"], commonMistakes: ["Rounding the lower back under load", "Turning the hinge into a squat by bending the knees too much"], alternatives: ["db-rdl", "barbell-deadlift"], progressionEasier: "hamstring-curl-machine", progressionHarder: "barbell-deadlift", videoUrl: null },
  { id: "db-rdl", name: "Dumbbell Romanian Deadlift", muscleGroup: "hamstrings", equipment: "dumbbell", difficulty: "intermediate", cue: "Slight knee bend, hinge back", cues: ["Slight knee bend, hinge back", "Push your hips back first, keeping a soft bend in the knees", "Keep the bar/weight close to your legs throughout"], commonMistakes: ["Rounding the lower back under load", "Turning the hinge into a squat by bending the knees too much"], alternatives: ["single-leg-rdl", "barbell-deadlift"], progressionEasier: "hamstring-curl-machine", progressionHarder: "barbell-deadlift", videoUrl: null },

  // Glutes
  { id: "db-step-up", name: "Dumbbell Step-Up", muscleGroup: "glutes", equipment: "dumbbell", difficulty: "beginner", cue: "Drive through front heel", cues: ["Drive through front heel", "Front knee tracks over the ankle, not past the toes", "Keep your torso upright rather than leaning forward"], commonMistakes: ["Letting the front knee cave inward on the way up", "Taking too short a step, putting excess stress on the front knee"], alternatives: ["glute-bridge", "band-glute-kickback"], progressionEasier: null, progressionHarder: "kb-swing", videoUrl: null },

  // Hamstrings
  { id: "barbell-deadlift", name: "Barbell Deadlift", muscleGroup: "hamstrings", equipment: "barbell", difficulty: "advanced", cue: "Neutral spine, push floor away", cues: ["Neutral spine, push floor away", "Push your hips back first, keeping a soft bend in the knees", "Keep the bar/weight close to your legs throughout"], commonMistakes: ["Rounding the lower back under load", "Turning the hinge into a squat by bending the knees too much"], alternatives: ["single-leg-rdl", "db-rdl"], progressionEasier: "single-leg-rdl", progressionHarder: null, videoUrl: null },
  { id: "hamstring-curl-machine", name: "Hamstring Curl Machine", muscleGroup: "hamstrings", equipment: "machine", difficulty: "beginner", cue: "Controlled curl, no hip lift", cues: ["Controlled curl, no hip lift", "Keep your hips pressed into the pad/bench throughout", "Curl through a full range without hip movement"], commonMistakes: ["Lifting the hips off the pad to cheat more range", "Using momentum instead of a controlled squeeze"], alternatives: ["single-leg-rdl", "db-rdl"], progressionEasier: null, progressionHarder: "single-leg-rdl", videoUrl: null },

  // Glutes
  { id: "kb-swing", name: "Kettlebell Swing", muscleGroup: "glutes", equipment: "kettlebell", difficulty: "intermediate", cue: "Hinge, snap hips forward", cues: ["Hinge, snap hips forward", "Power comes from the hip snap, not the arms or shoulders", "Keep the spine neutral — this is a hinge, not a squat"], commonMistakes: ["Squatting the swing instead of hinging at the hips", "Using the shoulders to lift the bell instead of hip drive"], alternatives: ["glute-bridge", "db-step-up"], progressionEasier: "glute-bridge", progressionHarder: null, videoUrl: null },
  { id: "band-glute-kickback", name: "Band Glute Kickback", muscleGroup: "glutes", equipment: "bands", difficulty: "beginner", cue: "Squeeze glute at full extension", cues: ["Squeeze glute at full extension", "Squeeze the glutes hard at the top of the movement", "Avoid overarching the lower back to get more range"], commonMistakes: ["Using lower back extension instead of glute contraction to move the weight", "Rushing through reps without pausing at peak contraction"], alternatives: ["glute-bridge", "db-step-up"], progressionEasier: null, progressionHarder: "kb-swing", videoUrl: null },

  // Calves
  { id: "calf-raise", name: "Standing Calf Raise", muscleGroup: "calves", equipment: "bodyweight", difficulty: "beginner", cue: "Full range, pause at top", cues: ["Full range, pause at top", "Rise all the way onto the balls of your feet", "Pause briefly at the top for a full contraction"], commonMistakes: ["Using a bouncy, fast tempo instead of a controlled one", "Cutting the range short at the top or bottom"], alternatives: ["db-calf-raise", "calf-raise-machine"], progressionEasier: null, progressionHarder: null, videoUrl: null },
  { id: "db-calf-raise", name: "Dumbbell Calf Raise", muscleGroup: "calves", equipment: "dumbbell", difficulty: "beginner", cue: "Slow tempo, full stretch at bottom", cues: ["Slow tempo, full stretch at bottom", "Rise all the way onto the balls of your feet", "Pause briefly at the top for a full contraction"], commonMistakes: ["Using a bouncy, fast tempo instead of a controlled one", "Cutting the range short at the top or bottom"], alternatives: ["calf-raise", "calf-raise-machine"], progressionEasier: null, progressionHarder: null, videoUrl: null },
  { id: "calf-raise-machine", name: "Calf Raise Machine", muscleGroup: "calves", equipment: "machine", difficulty: "beginner", cue: "Controlled through full range", cues: ["Controlled through full range", "Rise all the way onto the balls of your feet", "Pause briefly at the top for a full contraction"], commonMistakes: ["Using a bouncy, fast tempo instead of a controlled one", "Cutting the range short at the top or bottom"], alternatives: ["calf-raise", "db-calf-raise"], progressionEasier: null, progressionHarder: null, videoUrl: null },

  // Core
  { id: "plank", name: "Plank", muscleGroup: "core", equipment: "bodyweight", difficulty: "beginner", cue: "Straight line head to heels", cues: ["Straight line head to heels", "Keep a straight line from head to heels — no sagging hips", "Squeeze glutes and quads to help maintain the line"], commonMistakes: ["Letting the hips sag toward the floor as fatigue sets in", "Piking the hips up too high to make it easier"], alternatives: ["cable-crunch", "db-woodchopper"], progressionEasier: null, progressionHarder: "russian-twist", videoUrl: null },
  { id: "situp", name: "Sit-Up", muscleGroup: "core", equipment: "bodyweight", difficulty: "beginner", cue: "Controlled tempo, avoid neck strain", cues: ["Controlled tempo, avoid neck strain", "Curl the spine rather than yanking with your neck", "Keep the movement controlled on both the way up and down"], commonMistakes: ["Pulling on the neck with your hands instead of using the abs", "Using momentum/swinging instead of a controlled curl"], alternatives: ["cable-crunch", "db-woodchopper"], progressionEasier: null, progressionHarder: "russian-twist", videoUrl: null },
  { id: "russian-twist", name: "Russian Twist", muscleGroup: "core", equipment: "bodyweight", difficulty: "intermediate", cue: "Rotate from torso, feet may lift", cues: ["Rotate from torso, feet may lift", "Rotate through your torso, not just your arms", "Keep movements controlled — don't let momentum take over"], commonMistakes: ["Moving fast and using momentum instead of controlled rotation", "Rounding the lower back instead of rotating through the thoracic spine"], alternatives: ["db-woodchopper", "band-pallof-press"], progressionEasier: "plank", progressionHarder: "leg-raise", videoUrl: null },
  { id: "leg-raise", name: "Hanging/Lying Leg Raise", muscleGroup: "core", equipment: "bodyweight", difficulty: "advanced", cue: "Avoid swinging, control the descent", cues: ["Avoid swinging, control the descent", "Curl the spine rather than yanking with your neck", "Keep the movement controlled on both the way up and down"], commonMistakes: ["Pulling on the neck with your hands instead of using the abs", "Using momentum/swinging instead of a controlled curl"], alternatives: ["db-woodchopper", "band-pallof-press"], progressionEasier: "russian-twist", progressionHarder: null, videoUrl: null },
  { id: "mountain-climber", name: "Mountain Climber", muscleGroup: "core", equipment: "bodyweight", difficulty: "beginner", cue: "Keep hips low and stable", cues: ["Keep hips low and stable", "Keep a straight line from head to heels — no sagging hips", "Squeeze glutes and quads to help maintain the line"], commonMistakes: ["Letting the hips sag toward the floor as fatigue sets in", "Piking the hips up too high to make it easier"], alternatives: ["cable-crunch", "db-woodchopper"], progressionEasier: null, progressionHarder: "russian-twist", videoUrl: null },
  { id: "db-woodchopper", name: "Dumbbell Woodchopper", muscleGroup: "core", equipment: "dumbbell", difficulty: "intermediate", cue: "Rotate through torso, not just arms", cues: ["Rotate through torso, not just arms", "Rotate through your torso, not just your arms", "Keep movements controlled — don't let momentum take over"], commonMistakes: ["Moving fast and using momentum instead of controlled rotation", "Rounding the lower back instead of rotating through the thoracic spine"], alternatives: ["russian-twist", "band-pallof-press"], progressionEasier: "plank", progressionHarder: "leg-raise", videoUrl: null },
  { id: "cable-crunch", name: "Cable/Machine Crunch", muscleGroup: "core", equipment: "machine", difficulty: "beginner", cue: "Curl spine, not just pull with arms", cues: ["Curl spine, not just pull with arms", "Curl the spine rather than yanking with your neck", "Keep the movement controlled on both the way up and down"], commonMistakes: ["Pulling on the neck with your hands instead of using the abs", "Using momentum/swinging instead of a controlled curl"], alternatives: ["plank", "situp"], progressionEasier: null, progressionHarder: "russian-twist", videoUrl: null },
  { id: "band-pallof-press", name: "Band Pallof Press", muscleGroup: "core", equipment: "bands", difficulty: "intermediate", cue: "Resist rotation, press straight out", cues: ["Resist rotation, press straight out", "Rotate through your torso, not just your arms", "Keep movements controlled — don't let momentum take over"], commonMistakes: ["Moving fast and using momentum instead of controlled rotation", "Rounding the lower back instead of rotating through the thoracic spine"], alternatives: ["russian-twist", "db-woodchopper"], progressionEasier: "plank", progressionHarder: "leg-raise", videoUrl: null },
  { id: "kb-halo", name: "Kettlebell Halo", muscleGroup: "core", equipment: "kettlebell", difficulty: "intermediate", cue: "Circle bell around head, stay upright", cues: ["Circle bell around head, stay upright", "Rotate through your torso, not just your arms", "Keep movements controlled — don't let momentum take over"], commonMistakes: ["Moving fast and using momentum instead of controlled rotation", "Rounding the lower back instead of rotating through the thoracic spine"], alternatives: ["russian-twist", "db-woodchopper"], progressionEasier: "plank", progressionHarder: "leg-raise", videoUrl: null },

  // Cardio / Conditioning
  { id: "jumping-jacks", name: "Jumping Jacks", muscleGroup: "cardio", equipment: "bodyweight", difficulty: "beginner", cue: "Steady rhythm, land soft", cues: ["Steady rhythm, land soft", "Stay light on your feet with soft knees on landing", "Keep a steady, sustainable rhythm rather than sprinting immediately"], commonMistakes: ["Landing flat-footed and heavy, increasing joint stress", "Starting too fast and burning out within 30 seconds"], alternatives: ["kb-swing-cardio"], progressionEasier: null, progressionHarder: "kb-swing-cardio", videoUrl: null },
  { id: "burpee", name: "Burpee", muscleGroup: "cardio", equipment: "bodyweight", difficulty: "advanced", cue: "Full push-up, explosive jump", cues: ["Full push-up, explosive jump", "Keep the push-up portion full range if possible", "Land softly with bent knees on the jump"], commonMistakes: ["Skipping the chest-to-floor portion of the push-up", "Landing stiff-legged on the jump, jarring the knees"], alternatives: ["kb-swing-cardio"], progressionEasier: "kb-swing-cardio", progressionHarder: null, videoUrl: null },
  { id: "high-knees", name: "High Knees", muscleGroup: "cardio", equipment: "bodyweight", difficulty: "beginner", cue: "Drive knees to hip height", cues: ["Drive knees to hip height", "Stay light on your feet with soft knees on landing", "Keep a steady, sustainable rhythm rather than sprinting immediately"], commonMistakes: ["Landing flat-footed and heavy, increasing joint stress", "Starting too fast and burning out within 30 seconds"], alternatives: ["kb-swing-cardio"], progressionEasier: null, progressionHarder: "kb-swing-cardio", videoUrl: null },
  { id: "kb-swing-cardio", name: "Kettlebell Swing (conditioning)", muscleGroup: "cardio", equipment: "kettlebell", difficulty: "intermediate", cue: "Continuous hip-hinge rhythm", cues: ["Continuous hip-hinge rhythm", "Power comes from the hip snap, not the arms or shoulders", "Keep the spine neutral — this is a hinge, not a squat"], commonMistakes: ["Squatting the swing instead of hinging at the hips", "Using the shoulders to lift the bell instead of hip drive"], alternatives: ["jumping-jacks", "burpee"], progressionEasier: "jumping-jacks", progressionHarder: "burpee", videoUrl: null },
  { id: "shadow-boxing", name: "Shadow Boxing", muscleGroup: "cardio", equipment: "bodyweight", difficulty: "beginner", cue: "Stay light on feet, rotate hips on punches", cues: ["Stay light on feet, rotate hips on punches", "Stay light on your feet with soft knees on landing", "Keep a steady, sustainable rhythm rather than sprinting immediately"], commonMistakes: ["Landing flat-footed and heavy, increasing joint stress", "Starting too fast and burning out within 30 seconds"], alternatives: ["kb-swing-cardio"], progressionEasier: null, progressionHarder: "kb-swing-cardio", videoUrl: null },

  // --- Added from IBLITZ Master Exercise Database ---

  // Chest
  { id: "cable-fly", name: "Cable Fly", muscleGroup: "chest", equipment: "machine", difficulty: "intermediate", cue: "Slight elbow bend, squeeze at midline", cues: ["Slight elbow bend, squeeze at midline", "Lead with the chest, not the hands", "Control the eccentric — don't let the cables snap back"], commonMistakes: ["Bending the elbows too much, turning it into a press", "Using too much weight and losing the stretch at the bottom"], alternatives: ["db-flye", "pec-deck"], progressionEasier: "db-flye", progressionHarder: null, videoUrl: null },
  { id: "pec-deck", name: "Pec Deck", muscleGroup: "chest", equipment: "machine", difficulty: "beginner", cue: "Squeeze pecs together at the front", cues: ["Squeeze pecs together at the front", "Keep a slight bend in the elbows throughout", "Control the return instead of letting the pads snap back"], commonMistakes: ["Using momentum to swing the pads together", "Shrugging the shoulders up instead of keeping them down and back"], alternatives: ["cable-fly", "db-flye"], progressionEasier: null, progressionHarder: "cable-fly", videoUrl: null },
  { id: "machine-chest-press", name: "Machine Chest Press", muscleGroup: "chest", equipment: "machine", difficulty: "beginner", cue: "Press through mid-chest, don't lock out hard", cues: ["Press through mid-chest, don't lock out hard", "Keep shoulder blades pinned to the pad", "Drive through a full range without bouncing off the bottom"], commonMistakes: ["Flaring the elbows out to 90° and stressing the shoulders", "Bouncing the weight off the bottom stop instead of controlling it"], alternatives: ["db-bench-press", "chest-press-machine"], progressionEasier: null, progressionHarder: "barbell-bench-press", videoUrl: null },
  { id: "decline-press", name: "Decline Barbell Press", muscleGroup: "chest", equipment: "barbell", difficulty: "advanced", cue: "Lower to lower chest, elbows tucked slightly", cues: ["Lower to lower chest, elbows tucked slightly", "Keep feet locked under the footpads for stability", "Press in a slight arc back toward your face, not straight up"], commonMistakes: ["Bouncing the bar off the chest for extra momentum", "Flaring elbows to a full 90°, stressing the shoulder joint"], alternatives: ["barbell-bench-press", "db-bench-press"], progressionEasier: "barbell-bench-press", progressionHarder: null, videoUrl: null },

  // Back
  { id: "pullup", name: "Pull-Up", muscleGroup: "back", equipment: "bodyweight", difficulty: "advanced", cue: "Overhand grip, chest to bar", cues: ["Overhand grip, chest to bar", "Initiate by pulling the shoulder blades down and back", "Avoid kipping — control the descent fully"], commonMistakes: ["Using momentum/kipping instead of strict control", "Only completing half the range (not reaching full extension at bottom)"], alternatives: ["lat-pulldown", "bodyweight-row"], progressionEasier: "lat-pulldown", progressionHarder: null, videoUrl: null },
  { id: "tbar-row", name: "T-Bar Row", muscleGroup: "back", equipment: "barbell", difficulty: "intermediate", cue: "Chest up, row to lower ribs", cues: ["Chest up, row to lower ribs", "Keep the torso angle fixed — don't rock to generate momentum", "Squeeze the shoulder blades together at the top"], commonMistakes: ["Rounding the lower back under load", "Using body English/rocking instead of a strict pull"], alternatives: ["barbell-row", "cable-row"], progressionEasier: "db-row", progressionHarder: null, videoUrl: null },
  { id: "cable-row", name: "Seated Cable Row", muscleGroup: "back", equipment: "machine", difficulty: "beginner", cue: "Chest tall, pull to lower ribs", cues: ["Chest tall, pull to lower ribs", "Keep the torso angle fixed — don't rock to generate momentum", "Squeeze the shoulder blades together at the top"], commonMistakes: ["Rounding the lower back under load", "Using body English/rocking instead of a strict pull"], alternatives: ["band-row", "tbar-row"], progressionEasier: "band-row", progressionHarder: "tbar-row", videoUrl: null },
  { id: "rack-pull", name: "Rack Pull", muscleGroup: "back", equipment: "barbell", difficulty: "advanced", cue: "Pull from knee height, drive hips through", cues: ["Pull from knee height, drive hips through", "Keep the bar close to your shins throughout", "Lock out by driving the hips forward, not leaning back"], commonMistakes: ["Rounding the upper back at the top of the pull", "Using too much weight and turning it into a shrug"], alternatives: ["barbell-deadlift", "barbell-row"], progressionEasier: "barbell-row", progressionHarder: null, videoUrl: null },

  // Shoulders
  { id: "arnold-press", name: "Arnold Press", muscleGroup: "shoulders", equipment: "dumbbell", difficulty: "intermediate", cue: "Rotate palms out as you press up", cues: ["Rotate palms out as you press up", "Keep the core braced to avoid arching the lower back", "Control the rotation on the way down too"], commonMistakes: ["Using momentum/leg drive instead of shoulder strength", "Arching the back excessively to press the weight up"], alternatives: ["db-shoulder-press", "shoulder-press-machine"], progressionEasier: "db-shoulder-press", progressionHarder: null, videoUrl: null },
  { id: "rear-delt-fly", name: "Dumbbell Rear Delt Fly", muscleGroup: "shoulders", equipment: "dumbbell", difficulty: "beginner", cue: "Hinge forward, raise arms out to sides", cues: ["Hinge forward, raise arms out to sides", "Lead with the elbows, not the hands", "Keep a slight bend in the elbows throughout"], commonMistakes: ["Using momentum to swing the weights up", "Standing too upright, turning it into a lateral raise"], alternatives: ["band-lateral-raise", "db-lateral-raise"], progressionEasier: null, progressionHarder: null, videoUrl: null },
  { id: "push-press", name: "Push Press", muscleGroup: "shoulders", equipment: "barbell", difficulty: "advanced", cue: "Dip slightly, drive up with legs then press", cues: ["Dip slightly, drive up with legs then press", "Keep the dip short and vertical — not a squat", "Finish by locking the bar out overhead with the head through"], commonMistakes: ["Dipping too deep, turning it into a push jerk", "Pressing before the legs finish driving, losing the power transfer"], alternatives: ["db-shoulder-press", "barbell-ohp"], progressionEasier: "barbell-ohp", progressionHarder: null, videoUrl: null },
  { id: "face-pull", name: "Face Pull", muscleGroup: "shoulders", equipment: "bands", difficulty: "beginner", cue: "Pull to eye level, squeeze rear delts", cues: ["Pull to eye level, squeeze rear delts", "Lead with the elbows, pulling them high and wide", "Externally rotate at the end for full rear-delt engagement"], commonMistakes: ["Pulling low toward the chest instead of face height", "Using the biceps to pull instead of the rear delts/upper back"], alternatives: ["rear-delt-fly", "band-lateral-raise"], progressionEasier: null, progressionHarder: null, videoUrl: null },
  { id: "landmine-press", name: "Landmine Press", muscleGroup: "shoulders", equipment: "barbell", difficulty: "intermediate", cue: "Press up and slightly forward along the arc", cues: ["Press up and slightly forward along the arc", "Brace the core to avoid leaning back excessively", "Keep the supporting-side hip and shoulder stacked"], commonMistakes: ["Leaning back to help drive the press instead of using shoulder strength", "Letting the elbow flare out too wide at the bottom"], alternatives: ["db-shoulder-press", "push-press"], progressionEasier: "db-shoulder-press", progressionHarder: null, videoUrl: null },

  // Biceps / Triceps
  { id: "hammer-curl", name: "Hammer Curl", muscleGroup: "biceps", equipment: "dumbbell", difficulty: "beginner", cue: "Neutral grip, elbows pinned", cues: ["Neutral grip, elbows pinned", "Keep elbows locked at your sides throughout", "Curl with control — no swinging the torso"], commonMistakes: ["Swinging the torso to build momentum", "Letting the elbows drift forward away from the body"], alternatives: ["db-curl", "barbell-curl"], progressionEasier: null, progressionHarder: null, videoUrl: null },
  { id: "preacher-curl", name: "Preacher Curl", muscleGroup: "biceps", equipment: "barbell", difficulty: "intermediate", cue: "Full extension at bottom, no swinging", cues: ["Full extension at bottom, no swinging", "Keep the upper arms flat against the pad", "Don't fully lock out the elbows at the bottom under load"], commonMistakes: ["Bouncing out of the bottom stretch position", "Lifting the upper arms off the pad to cheat extra range"], alternatives: ["barbell-curl", "db-curl"], progressionEasier: "db-curl", progressionHarder: null, videoUrl: null },
  { id: "jm-press", name: "JM Press", muscleGroup: "triceps", equipment: "barbell", difficulty: "advanced", cue: "Lower toward chin, elbows tracking forward", cues: ["Lower toward chin, elbows tracking forward", "Keep elbows tucked rather than flaring out", "Control the descent — this isn't a bounce movement"], commonMistakes: ["Flaring the elbows out wide, turning it into a bench press", "Using too much weight and losing control of the bar path"], alternatives: ["tricep-pushdown", "diamond-pushup"], progressionEasier: "tricep-pushdown", progressionHarder: null, videoUrl: null },
  { id: "weighted-dip", name: "Weighted Dip", muscleGroup: "triceps", equipment: "bodyweight", difficulty: "advanced", cue: "Lean slightly forward, lower under control", cues: ["Lean slightly forward, lower under control", "Keep elbows tracking backward, not flared out", "Stop around 90° at the bottom to protect the shoulders"], commonMistakes: ["Descending too deep and straining the shoulder joint", "Flaring the elbows out wide instead of keeping them back"], alternatives: ["tricep-dip", "diamond-pushup"], progressionEasier: "tricep-dip", progressionHarder: null, videoUrl: null },

  // Quads / Hamstrings
  { id: "front-squat", name: "Front Squat", muscleGroup: "quads", equipment: "barbell", difficulty: "advanced", cue: "Elbows high, torso upright", cues: ["Elbows high, torso upright", "Keep the bar resting on the front delts, not the hands", "Sit straight down rather than back, staying upright"], commonMistakes: ["Letting the elbows drop, causing the bar to roll forward", "Leaning too far forward, losing the upright torso position"], alternatives: ["barbell-squat", "db-goblet-squat"], progressionEasier: "db-goblet-squat", progressionHarder: null, videoUrl: null },
  { id: "barbell-rdl", name: "Barbell Romanian Deadlift", muscleGroup: "hamstrings", equipment: "barbell", difficulty: "intermediate", cue: "Hinge back, bar stays close to legs", cues: ["Hinge back, bar stays close to legs", "Push your hips back first, keeping a soft bend in the knees", "Keep the bar/weight close to your legs throughout"], commonMistakes: ["Rounding the lower back under load", "Turning the hinge into a squat by bending the knees too much"], alternatives: ["db-rdl", "single-leg-rdl"], progressionEasier: "db-rdl", progressionHarder: "barbell-deadlift", videoUrl: null },
  { id: "hack-squat", name: "Hack Squat Machine", muscleGroup: "quads", equipment: "machine", difficulty: "intermediate", cue: "Feet mid-platform, knees track over toes", cues: ["Feet mid-platform, knees track over toes", "Control the descent — don't let the sled drop", "Drive evenly through the whole foot, not just the toes"], commonMistakes: ["Letting the knees cave inward under load", "Only using a partial range of motion at the top"], alternatives: ["leg-press", "barbell-squat"], progressionEasier: "leg-press", progressionHarder: "front-squat", videoUrl: null },

  // Core
  { id: "ab-wheel", name: "Ab Wheel Rollout", muscleGroup: "core", equipment: "bodyweight", difficulty: "advanced", cue: "Brace hard, roll out without arching", cues: ["Brace hard, roll out without arching", "Keep the lower back flat — stop before it arches", "Pull back in using the abs, not the hip flexors"], commonMistakes: ["Letting the lower back sag/arch during the rollout", "Rolling out too far before building the strength to control it"], alternatives: ["plank", "leg-raise"], progressionEasier: "plank", progressionHarder: "dragon-flag", videoUrl: null },
  { id: "dragon-flag", name: "Dragon Flag", muscleGroup: "core", equipment: "bodyweight", difficulty: "advanced", cue: "Body straight, lower under total control", cues: ["Body straight, lower under total control", "Keep the whole body rigid as a single unit", "Only lower as far as you can control without the hips sagging"], commonMistakes: ["Letting the hips sag or bend during the lower", "Dropping too fast instead of a slow, controlled descent"], alternatives: ["leg-raise", "ab-wheel"], progressionEasier: "leg-raise", progressionHarder: null, videoUrl: null },
  { id: "turkish-getup", name: "Turkish Get-Up", muscleGroup: "core", equipment: "kettlebell", difficulty: "advanced", cue: "Eyes on the bell, move through each step deliberately", cues: ["Eyes on the bell, move through each step deliberately", "Keep the arm locked out vertically throughout", "Move slowly — this is a control drill, not a speed drill"], commonMistakes: ["Rushing through the steps instead of controlling each position", "Letting the locked-out arm drift away from vertical"], alternatives: ["kb-halo", "plank"], progressionEasier: "kb-halo", progressionHarder: null, videoUrl: null },

  // Cardio / Conditioning
  { id: "jump-rope", name: "Jump Rope", muscleGroup: "cardio", equipment: "bodyweight", difficulty: "beginner", cue: "Small hops, stay on the balls of your feet", cues: ["Small hops, stay on the balls of your feet", "Keep jumps low and quick rather than high", "Rotate the rope from the wrists, not the whole arm"], commonMistakes: ["Jumping too high, wasting energy and increasing impact", "Using the shoulders/arms to turn the rope instead of the wrists"], alternatives: ["high-knees", "jumping-jacks"], progressionEasier: "jumping-jacks", progressionHarder: "box-jump", videoUrl: null },
  { id: "sprint", name: "Sprint Intervals", muscleGroup: "cardio", equipment: "bodyweight", difficulty: "intermediate", cue: "Drive knees, pump arms, full effort", cues: ["Drive knees, pump arms, full effort", "Stay relaxed through the shoulders and face", "Allow full recovery between reps to sustain quality"], commonMistakes: ["Not fully recovering between sprints, degrading form and speed", "Overstriding, which increases hamstring injury risk"], alternatives: ["high-knees", "kb-swing-cardio"], progressionEasier: "high-knees", progressionHarder: null, videoUrl: null },
  { id: "row-erg", name: "Rowing Machine", muscleGroup: "cardio", equipment: "machine", difficulty: "beginner", cue: "Legs drive first, then lean, then pull", cues: ["Legs drive first, then lean, then pull", "Sequence each stroke: legs → hips → arms", "Reverse the sequence on the way back: arms → hips → legs"], commonMistakes: ["Pulling with the arms before the legs finish driving", "Rounding the lower back at the catch position"], alternatives: ["kb-swing-cardio", "jump-rope"], progressionEasier: null, progressionHarder: null, videoUrl: null },
  { id: "box-jump", name: "Box Jump", muscleGroup: "cardio", equipment: "bodyweight", difficulty: "advanced", cue: "Land soft with bent knees, step down don't jump down", cues: ["Land soft with bent knees, step down don't jump down", "Land with the whole foot, not just the toes", "Always step back down — don't jump down to save the joints"], commonMistakes: ["Jumping back down off the box, which is harder on the joints than the jump itself", "Landing stiff-legged instead of absorbing with bent knees"], alternatives: ["jump-rope", "high-knees"], progressionEasier: "jump-rope", progressionHarder: null, videoUrl: null },
];
